# Generated by Django 5.2.8 on 2025-11-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cellphone_number",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
